spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
  cloud:
    gateway:
      routes:
        - id: spring-6-rest-mvc
          uri: http://rest-mvc-service:8080
          predicates:
            - Path=/api/v1/*/**
        - id: spring-6-reactive
          uri: http://reactive-service:8080
          predicates:
            - Path=/api/v2/*
        - id: spring-6-reactive-mongo
          uri: http://reactive-mongo-service:8080
          predicates:
            - Path=/api/v3/*
        - id: spring-6-auth-server
          uri: http://auth-server:9000
          predicates:
            - Path=/oauth2/*
management:
  endpoint:
      health:
        probes:
          enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
        enabled: true
# ENABLE BELOW FOR TROUBLESHOOTING
#      httpserver:
#        wiretap: true
#      httpclient:
#        wiretap: true
#logging:
#  level:
#    root: error
#    reactor.netty: trace
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: trace